### ISSUE TITLE
LLVM Version

### ISSUE THREAD

**Issue by ArmageddonKnight** [tlc-pack/TLCBench#4]
Hi,

I was trying to reproduce the performance results on g4dn.4xlarge instance but got the following error:

```
~/TLCBench$ python3 benchmark_autoscheduler.py --network bert --target "cuda -model=t4"  --logdir saved_logs/latest
Benchmark bert-B1-float32 ...
python3: /tmp/build/80754af9/llvmdev_1560805331146/work/lib/ExecutionEngine/MCJIT/MCJIT.cpp:204: virtual void llvm::MCJIT::generateCodeForModule(llvm::Module*): Assertion `M->getDataLayout() == getDataLayout() && "DataLayout Mismatch"' failed.
Aborted (core dumped)
```

My speculation is that the issue might be caused by LLVM version incompatibility. Would you mind sharing the LLVM version that you are using? I have been using LLVM Ver. 10.

**Comment by junrushao** [comment]
I am using LLVM 11.1 and it seems to work

**Comment by ArmageddonKnight** [comment]
@junrushao1994 I see. Let me try to switch to LLVM 11.1.
